# development:
#   password: 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
#   theme_id: "117985968314"
#   store: panacchebeta.myshopify.com

development:
  password: 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
  theme_id: "122359087263"
  store: panacchedev.myshopify.com

